public with sharing class UpdateStatusHepper {
    public static void checkUpdateStatusHepper(List<F_TMS_SO__c> newList, Map<Id,F_TMS_SO__c> oldMap) {
        // for (F_TMS_SO__c so : newList) {
        //     if(so.Schedule_Record_Type__c != oldMap.get(so.Id).Schedule_Record_Type__c){
        //         so.Schedule_Record_Type_Text__c = so.Schedule_Record_Type__c;
        //     }
        // }
    }   
}